name: qr_scanner
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  responsive_sizer: ^3.1.1
  url_launcher: ^6.1.7
  flutter_speed_dial: ^6.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.3.2
  flutter_generator: ^1.0.5
  flutter_launcher_icons: ^0.11.0
  hive_generator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:

  android: true
  ios: true
  image_path: "lib/assets/codigo_qr.png"
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/camera.png
    - lib/assets/flash_apagado.png
    - lib/assets/flash.png
    - lib/assets/barcode.png
    - lib/assets/codigo_qr.png


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #